AWSTemplateFormatVersion: '2010-09-09'
Description: RDS PostgreSQL for EcomMicroservices
Parameters:
  ProjectName:
    Type: String
    Default: ecom-microservices
  Environment:
    Type: String
    Default: prod
  DBPassword:
    Type: String
    NoEcho: true
  DBInstanceClass:
    Type: String
    Default: db.t3.medium
Resources:
  RDSMonitoringRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: monitoring.rds.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole
  RDSSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: RDS subnet group
      SubnetIds:
        - !ImportValue
          Fn::Sub: ${ProjectName}-${Environment}-DataSubnetA
        - !ImportValue
          Fn::Sub: ${ProjectName}-${Environment}-DataSubnetB
        - !ImportValue
          Fn::Sub: ${ProjectName}-${Environment}-DataSubnetC
  RDSInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    Properties:
      DBInstanceIdentifier: !Sub ${ProjectName}-${Environment}-postgres
      DBInstanceClass: !Ref DBInstanceClass
      Engine: postgres
      EngineVersion: '15.10'
      MasterUsername: ecomadmin
      MasterUserPassword: !Ref DBPassword
      DBName: postgres
      AllocatedStorage: '100'
      StorageType: gp3
      StorageEncrypted: true
      MultiAZ: true
      DBSubnetGroupName: !Ref RDSSubnetGroup
      VPCSecurityGroups:
        - !ImportValue
          Fn::Sub: ${ProjectName}-${Environment}-RDSSecurityGroup
      BackupRetentionPeriod: 7
      DeletionProtection: false
      EnablePerformanceInsights: true
      MonitoringInterval: 60
      MonitoringRoleArn: !GetAtt RDSMonitoringRole.Arn
Outputs:
  RDSEndpoint:
    Value: !GetAtt RDSInstance.Endpoint.Address
    Export:
      Name: !Sub ${ProjectName}-${Environment}-RDSEndpoint
